### ISSUE TITLE
Some HMM models not found. 

### ISSUE THREAD

**Issue by pollyhere** [fannyhb/fargene#14]
Hi Fanny,

I managed to run the models until Tetracycline resistance genes, anything beyond returned with an error msg below:

> CRITICAL: 
> The HMM file model_a could not be found.
> Either provide a valid path to a HMM or choose one of the following pre-defined models:
> b1
> class_b_1_2
> class_b_3
> class_a
> class_c
> class_d_1
> class_d_2
> qnr
> tet_efflux
> tet_rpg
> tet_enzyme
> INFO: Exiting pipeline
> 

May I know if the rest of the models still available or it is until tet_enzyme only?

Thanks!

-Polly_

**Comment by fannyhb** [comment]
Hi Polly,

The new models aren't included in the conda package yet, so if you want to get access to those you need to clone the repo from github.

best regards,
Fanny
