### ISSUE TITLE
CRITICAL: Did not find transeq in path.

### ISSUE THREAD

**Issue by This12** [fannyhb/fargene#3]
I use "./fargene_analysis.py -i path/to/fastafile(s)/*.fasta --hmm-model class_a -o output_dir" with my sequence.fasta, but it comes to "CRITICAL: Did not find transeq in path." "Exiting pipeline".
And I lack some files or step?

**Comment by bl4val** [comment]
You need to have [transeq](http://emboss.sourceforge.net/download/) installed and in your [path](https://en.wikipedia.org/wiki/PATH_(variable)) (most installers add to the path automatically). See the [readme](https://github.com/fannyhb/fargene/blob/master/README.md) for more info and install the needed prerequisites.
