### ISSUE TITLE
fARGene run error : IndexError: list index out of range

### ISSUE THREAD

**Issue by P-kai** [fannyhb/fargene#8]
INFO: Starting fARGene
INFO: Starting pipeline, planning to analyze 1 files
INFO: Running on 20 processes
INFO: Starting parse_fastq_input
INFO: Converting FASTQ to FASTA
INFO: Processing and searching input files. This may take a while...
[]
INFO: Converting fastq to fasta
INFO: Translating and searching
INFO: Start to classify
INFO:fargene_analysis.fargene_analysis.pooled_processing_fastq:Start to classify
INFO: Translating, searching, and classification done
INFO:fargene_analysis.fargene_analysis.pooled_processing_fastq:Translating, searching, and classification done
Traceback (most recent call last):
  File "/home/dell/anaconda2/bin/fargene", line 11, in <module>
    load_entry_point('fargene==0.1', 'console_scripts', 'fargene')()
  File "/home/dell/anaconda2/lib/python2.7/site-packages/fargene-0.1-py2.7.egg/fargene_analysis/fargene_analysis.py", line 190, in main
    parse_fastq_input(options, Results, logger)
  File "/home/dell/anaconda2/lib/python2.7/site-packages/fargene-0.1-py2.7.egg/fargene_analysis/fargene_analysis.py", line 415, in parse_fastq_input
    transformer.find_file_difference(options.infiles[0], options.infiles[1])
IndexError: list index out of range

**Comment by boulund** [comment]
@P-kai, Could you please share the command line you used to run fARGene?

**Comment by P-kai** [comment]
$ fargene -i all.fastq --meta --hmm-model class_a -o out_dir -p 20





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Fredrik Boulund"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月6日(星期一) 下午3:13
收件人:&nbsp;"fannyhb/fargene"<fargene@noreply.github.com&gt;;
抄送:&nbsp;"彭凯"<729943115@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [fannyhb/fargene] fARGene run error : IndexError: list index out of range (#8)





 
@P-kai, Could you please share the command line you used to run fARGene?

**Comment by boulund** [comment]
Ah, it looks like you are using only a single input file. fARGene requires at least two input files for FASTQ data (paired end FASTQ in two files expected; forward and reverse). Please review the instructions in the README again and come back if you are still stuck.

https://github.com/fannyhb/fargene#data-analysis

**Comment by P-kai** [comment]
en...ok. Thanks you! So it couldn't be used to analyze nanopore sequence?
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Fredrik Boulund"<notifications@github.com&gt;; 
发送时间: 2020年7月6日(星期一) 下午5:58
收件人: "fannyhb/fargene"<fargene@noreply.github.com&gt;; 
抄送: "彭凯"<729943115@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [fannyhb/fargene] fARGene run error : IndexError: list index out of range (#8)





 
Ah, it looks like you are using only a single input file. fARGene requires at least two input files for FASTQ data (paired end FASTQ in two files expected; forward and reverse). Please review the instructions in the README again and come back if you are still stuck.
 
https://github.com/fannyhb/fargene#data-analysis

**Comment by boulund** [comment]
If you convert the long reads to FASTA you should be able to run fARGene using the FASTA data instead. The quality of the results will depend on the quality of your data. If possible, you could consider assembling the long read data you have, and provide fARGene with contigs.
